// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearFiles():Promise<void>;

export function GerarArquivos():Promise<string>;

export function SelectDirSaida():Promise<string>;

export function SelectModelFile():Promise<string>;

export function SelectRelacaoFile():Promise<string>;
