// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearFiles() {
  return window['go']['main']['App']['ClearFiles']();
}

export function GerarArquivos() {
  return window['go']['main']['App']['GerarArquivos']();
}

export function SelectDirSaida() {
  return window['go']['main']['App']['SelectDirSaida']();
}

export function SelectModelFile() {
  return window['go']['main']['App']['SelectModelFile']();
}

export function SelectRelacaoFile() {
  return window['go']['main']['App']['SelectRelacaoFile']();
}
